### PR TITLE
Makes toyplot work with python 3.10 due to an API change in collections

### PR DESCRIPTION
**Pull request by StuntsPT**
Using toyplot with python 3.10 was causing the following exception:

``` traceback
File "/home/francisco/.local/lib/python3.10/site-packages/toyplot/color.py", line 200, in broadcast
    if isinstance(colors, collections.Sequence):
AttributeError: module 'collections' has no attribute 'Sequence'
```

Investigating the issue led me to realize this was due to a change in the [collections module](https://docs.python.org/3/library/collections.abc.html).
The class `Sequence` was moved from `collections.Sequence` to `collections.abc.Sequence`.
This PR fixes the issue by calling the `Sequence` class from the "new" module.
I did not test it, but according to the documentation, this should be compatible with python 3.3 and up.

Best,

Francisco

### CODE REVIEW

**Comment by tshead2** [comment]
@StuntsPT - great job tracking this down.  Many thanks!

Tim

**Comment by StuntsPT** [comment]
Happy to help!
